@extends('layouts.app')
@section('mytitle', 'Terms of Use')
@section('content')
<div class="container marketing">
<h1 class="mt-5">Terms of Use</h1>
<p><em>As published: August 17, 2021</em></p>
<p>Please read these Terms of Use (“Terms of Use”) carefully. Tiberium Investments, LP, a registered investment adviser to the Tiberium Investments owns and operates the investment advisory portions of this website, https://Tiberium Investments-funds.com/ (“Site”). By registering for, logging into, visiting and/or otherwise using the Site in any way, you indicate that you understand and intend these Terms of Use to be the legal equivalent of a signed, written contract, and you accept these terms of use herein and agree to be legally bound by them. If you do not agree to these Terms and Conditions, please do not access this Site or any pages thereof.</p>
<p><strong>Reservation of Rights </strong><br />
We reserve the right, at our discretion, to change, modify, add, or remove portions of these Terms of Use at any time. Your continued use of the Site following reasonable notice of such modifications will be conclusively deemed acceptance of any changes to these Terms of Use. You agree that notice of changes to these Terms and Conditions posted on the Site constitutes reasonable and sufficient notice. At all times, you are bound by the then-current version of the Terms of Use and of all applicable laws.</p>
<p><strong>Use of Content </strong><br />
The Content (as defined below) of this Site is available for informational purposes only. The posting of Content and access to this Site does not constitute, either explicitly or implicitly, any provision of services or products by Tiberium Investments.</p>
<p><strong>Copyright and TrademTiberium Investmentss </strong><br />
This Site (including the software and files), the computers hosting this Site, and content provided on this Site, including any text, music and sound, graphics, images, photographs, audio and video, footage, animations, podcasts, analyses, studies, reports, and downloads (all such content collectively, the “Content”) are the exclusive property of Tiberium Investments, are licensed to Tiberium Investments, or are <a class="fipop" href="https://creativecommons.org/" target="_blank" rel="noopener">publicly copyrighted</a>, and are protected by law, including United States copyright, database, trade secret, and trademTiberium Investments law, as well as other state, national, and international laws and regulations. Tiberium Investments is a trademTiberium Investments or registered trademTiberium Investments in the United States and throughout the world. Tiberium Investments reserves all rights with respect to its proprietary information or material on this Site and will enforce such rights to the full extent of applicable copyright and trademTiberium Investments law. Except as expressly provided in these Terms of Use, Tiberium Investments does not grant any express or implied rights to you. All rights in the pages and Content are owned by Tiberium Investments and their respective licensors. You agree not to sell, distribute, publish, broadcast, circulate or commercially exploit Content in any manner without the express written consent of Tiberium Investments. Any downloading or otherwise copying from this Site will not transfer title to any software or material to you. Unless otherwise noted, Tiberium Investments, and other brands featured on the Site constitute our trade/service mTiberium Investmentss. You agree not to, directly or indirectly, attempt to register, challenge or contest the validity of Tiberium Investments’s ownership of, such copyrights, trademTiberium Investmentss or any other intellectual property of Tiberium Investments, or assist any third party in doing so.</p>
<p><strong>Grant of License </strong><br />
Tiberium Investments grants to you a personal, revocable, nonexclusive, nontransferable license to use this Site conditioned on your continued compliance with these Terms of Use. Limited portions of the Content available in the public areas of the Site may be accessed, printed and downloaded on an occasional basis for personal, scholarly, research or non-commercial purposes; provided that all hard copies contain all copyright and other applicable proprietary rights notices included in such content and information and/or appropriate attribution to Tiberium Investments in a form and manner acceptable to Tiberium Investments. For information on obtaining permission to use any Content beyond the uses permitted above, please contact Tiberium Investments – 3E 28th Street, Floor 7, New York, NY 10016. Unless and except as otherwise expressly permitted by these Terms of Use, you may not access, copy, reproduce, modify, create derivative works of, alter, publicly distribute, republish, upload, post, transmit, publicly perform or display, license, transfer, sell, mirror, frame, “deep link,” “scrape,” data mine, or otherwise use any information or material obtained from or through this Site, without written permission from Tiberium Investments. Any unauthorized use of this Site or the Content, or any violation of applicable laws, will terminate the permission granted herein.</p>
<p><strong>No Offer</strong><br />
Nothing contained herein constitutes an offer, solicitation or recommendation regarding any investment management product or service, or the offer to sell or the solicitation of an offer to buy any security; nor shall any such services be provided, or securities be offered or sold, in any jurisdiction in which such an offer, solicitation, provision or sale would be unlawful. All Site Content is subject to applicable statutes and regulations. This Site is published in the United States for residents of the United States. Investors outside of the United States are subject to securities and tax regulations within their applicable jurisdictions that are not addressed on this Site. U.S. investors are advised that not all investments or services described on this Site are available for sale in all states. Any potential investor should satisfy himself that an investment in an Tiberium Investments product is permissible under the rules and regulations of his or her domicile. The Site is not directed to any person in any jurisdiction where (by reason of that person’s nationality, residence or otherwise) the publication or availability of the Site is prohibited. Persons in respect of whom such prohibitions apply must not access the Site.</p>
<p>Any reference to a particular company or security is not an endorsement by Tiberium Investments of that company or security or a recommendation by Tiberium Investments to purchase or sell such security. The information provided is for informational purposes only and investors should determine for themselves whether a particular service or product is suitable for their investment needs or should seek such professional advice for their particular situation. Please refer to offering documents for further information concerning specific products.</p>
<p>Certain of the statements contained herein may be statements of future expectations and other forward-looking statements that are based on Tiberium Investments’s current views and assumptions and involve known and unknown risks and uncertainties that could cause actual results, performance or events to differ materially from those expressed or implied in such statements. In addition to statements which are forward-looking by reason of context, the words “may, will, should, expects, plans, intends, anticipates, believes, estimates, predicts, potential, or continue” and similar expressions identify forward-looking statements.</p>
<p>The matters discussed herein may also involve risks and uncertainties described from time to time in Tiberium Investments’s filings with the U.S. Securities and Exchange Commission. The company assumes no obligation to update any forward-looking information contained herein.</p>
<p><strong>Investments </strong><br />
Past performance is no guarantee of future results. Equities may decline in value due to both real and perceived general mTiberium Investmentset, economic, and industry conditions. The value of investments, and the income from them, can go down as well as up, and you may not recover the amount of your original investment. Any tax benefits referred to on this Site are subject to change and their availability and value will depend on your individual circumstance. Such investments are not deposits or obligations of, or guaranteed or endorsed by, any bank, and are not federally insured or guaranteed by the U.S. government, the FDIC, the Federal Reserve Board or any other agency. Some Tiberium Investments products may not be available in or appropriate for a retirement savings plan. Please contact your financial adviser about any investment restrictions associated with your particular plan.</p>
<p><strong>No Reliance </strong><br />
Although Tiberium Investments has taken reasonable care to ensure that the information contained within this Site is accurate, no representation or warranty (including liability towards third parties), expressed or implied, is made as to its accuracy, reliability or completeness by Tiberium Investments or their contractual partners. Opinions and any other Content are provided by Tiberium Investments for personal use and informational purposes only and are subject to change without notice. Nothing contained on this Site constitutes investment, legal, tax or other advice and is not to be relied on in making an investment or other decision.</p>
<p><strong>No Warranty </strong><br />
The information and opinions contained on this Site, including hyperlinks or references to other sites, are provided ‘as is’ without any warranty of any kind, either expressed or implied, to the fullest extent permissible pursuant to applicable law. You are responsible for evaluating the adequacy, accuracy, reliability, merchantability, non-infringement, completeness of any information or the content available on the Site or fitness for any particular purpose with respect to the Site or any of its Content. Tiberium Investments further assumes no responsibility for, and makes no warranties that, functions contained on this Site will be uninterrupted or error-free, that defects will be corrected, or that this Site or the servers that make it available will be free of viruses or other harmful components.</p>
<p><strong>Liability Waiver</strong><br />
Neither Tiberium Investments nor any of their respective affiliates, directors, officers, registered representatives or employees, nor any third party vendor, will be liable or have any liability, whether in contract, tort, strict liability or otherwise, for any direct, indirect, incidental, consequential, punitive or special damages arising out of or in any way connected with your access or use or inability to access or use the Site or reliance on the Content, or any failure of performance, interruption, defect, delay in transmission, computer viruses or other harmful components, or line or system failure associated with the site, regardless of our knowledge thereof.</p>
<p>Where applicable law does not permit the limitation of liability, implied warranties or the exclusion or limitation of certain damages set forth above, the aggregate liability of Tiberium Investments shall not exceed one hundred dollars ($100).</p>
<p><strong>Indemnification</strong><br />
You hereby indemnify, defend, and hold Tiberium Investments and any of their respective affiliates, directors, officers, registered representatives or employees, nor any third party vendor harmless from and against any and all liabilities, judgments, fines, damages, settlements and costs (including reasonable attorneys&#8217; fees and disbursements) incurred in connection with any claim arising out of any breach by you of these Terms of Use or claims arising from your use of this Site. You will cooperate with us in the defense of any claim. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you.</p>
<p><strong>Events Beyond Tiberium Investments’s Control </strong><br />
You expressly absolve and release Tiberium Investments and all of its officers, directors, employees, registered representatives, shareholders, legal representatives, attorneys, agents, successors and assigns, from any claim of harm resulting from a cause beyond its control including, but not limited to, the failure of electronic or mechanical equipment or communication lines, telephone or other interconnect problems, computer viruses or software failures, unauthorized access, theft, operator errors, severe weather, earthquakes, or natural disasters, strikes or other labor problems, wars, acts of domestic or foreign terrorism or governmental restrictions. Tiberium Investments does not warrant that this Site will be available at any time or that your access to this Site will be uninterrupted, timely or free from viruses or other harmful components. Tiberium Investments reserves the right to cease operating this website or to terminate your access and use of any part of this Site at any time without notice and for any reason.</p>
<p><strong>User Representations </strong><br />
You represent and warrant to Tiberium Investments that you will not use this Site for any purpose that is unlawful or prohibited by these Terms of Use, including but not limited to attempting or actually: (a) disrupting, impairing or otherwise interfering with the operation or integrity of the Site or circumventing any Site security system; (b) collecting any information about other users of the Site; (c) systematically, or by any automated means, extracting Content or other information or data contained in the Site to populate databases or other sites; or (d) engaging in any fraudulent or manipulative activity with respect to issuers, securities or mTiberium Investmentsets. Tiberium Investments may terminate your access and use of any part of the Site for such violations.</p>
<p><strong>Linked Sites</strong><br />
Certain hyperlinks or referenced websites on the Site may for your convenience forward you to third parties’ websites, which generally are recognized by their top level domain name. Any descriptions of, references to, or links to other products, publications or services do not constitute an endorsement, authorization, sponsorship by or affiliation with Tiberium Investments with respect to any linked site or its sponsor, unless expressly stated by Tiberium Investments. Any such information, products or sites have not necessarily been reviewed by Tiberium Investments and are provided or maintained by third parties over whom Tiberium Investments exercises no control. Tiberium Investments expressly disclaims any responsibility for the content, the accuracy of the information, and/or quality of products or services provided by or advertised on these third-party sites. Tiberium Investments reserves the right to terminate any hyperlink or hyperlinking program at any time.</p>
<p><strong>Information Submitted By You</strong><br />
Tiberium Investments’s usage of your personal information is governed by our <a href="https://Tiberium Investments-funds.com/privacy-policy" target="_blank" rel="noopener">Privacy Policy</a>, which forms part of these Terms of Use. You should not submit any confidential or proprietary information via the Site. By submitting any information or material to us through the Site, you grant us an unrestricted, irrevocable, worldwide, royalty-free, non-exclusive license to use, reproduce, display, perform, modify, transmit and distribute those materials or information. You also agree that Tiberium Investments is free to use for any purpose any ideas, concepts, know-how or techniques that you submit to us through the Site. Tiberium Investments shall not be subject to any obligations of confidentiality regarding submitted information, except as agreed to by Tiberium Investments or as otherwise specifically agreed or required by law. You agree not to use this Site to upload, display or distribute any materials that are defamatory, threatening, obscene, harassing, or otherwise unlawful, or that incorporate the copyrighted, confidential or proprietary material of any other person or entity.</p>
<p><strong>Jurisdiction, Severability </strong><br />
Any action arising out of these Terms of Use or the Site shall be litigated in, and only in, courts located in New York, and you agree to submit to the exclusive jurisdiction of those courts and further agree that they are a convenient forum for you.</p>
<p>In the event that any provision of these terms is held unenforceable, the validity or enforceability of the remaining provisions will not be affected, and the unenforceable provision will be replaced with an enforceable provision that comes close to the intention underlying the unenforceable provision.</p>
<p><strong>Social Media Disclosure </strong><br />
Tiberium Investments’s social media accounts are run by individual analysts or other Tiberium Investments team members. Social media posts are not necessarily the opinion of Tiberium Investments as a whole. As a thematic investor, Tiberium Investments and its related persons (including Kenny Lock), use social media conversations, including those on Twitter, as part of its investment research process. As a result, Tiberium Investments and clients as well as its related persons such as Kenny Lock may (but do not necessarily) have financial interests in securities or issuers that we discuss. However, any discussion of securities or issuers by Tiberium Investments or Kenny Lock in such conversations is not a recommendation to buy, sell or hold any particular security.</p>
<p>The Tiberium Investments may tweet information about the ETFs, including portfolio holdings information.  Portfolio holdings in the ETFs are subject to change without notice and reference to a specific holding is not a recommendation to buy, sell or hold any particular security.  Tiberium Investments’s ETFs’ holdings can be accessed here: <a href="https://Tiberium Investments-funds.com/investor-resources" target="_blank" rel="noopener">Investor Resources</a></p>
</div>
@endsection